export const LINK_RESIDENCIAL = "https://wwws.portoseguro.com.br/vendaonline/residencia/home.ns?cod=adcf3c68904240318ac55b9cbcd858a3&utm_source=7860JJ&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_NY93YJ&utm_content=LIBERO_CORRETORA_LTDA"
export const LINK_PORTATEIS = "https://wwws.portoseguro.com.br/vendaonline/equipamentosportateis/home.ns?cod=30ae4dc4316042f68282bf79ab70aa63&utm_source=7860JJ&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_NY93YJ&utm_content=LIBERO_CORRETORA_LTDA"
export const LINK_VIDA_INDIVIDUAL = "https://wwws.portoseguro.com.br/vendaonline/vidamaissimples/home.ns?cod=fb671ed2e60546aaab388c91194a6cfc&utm_source=7860JJ&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_NY93YJ&utm_content=LIBERO_CORRETORA_LTDA"
export const LINK_VIAGEM = "https://wwws.portoseguro.com.br/vendaonline/viagem/home.ns?cod=a68f1013d67b48968f20d604a7507b86&utm_source=7860JJ&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_NY93YJ&utm_content=LIBERO_CORRETORA_LTDA"
export const LINK_ODONTOLOGICO = "http://sulamericaodonto.com.br/liberosegs"
export const LINK_BIKE = "https://www.berkley.com.br/PortalSegurado/Bike/Home.html#/LBRO"

export const LINK_AUTO = "/seguro/auto"
export const LINK_AGRICOLAS = "/seguro/riscosagricolas"
export const LINK_CARGAS = "/seguro/cargas"
export const LINK_EMPRESARIAL = "/seguro/empresarial"
export const LINK_CONDOMINIO = "/seguro/empresarial"
export const LINK_FINANCIAMENTOS = "/seguro/financiamentos"
export const LINK_LIGACAO = "/seguro/ligacao"
